[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["GravDev <107803920+thegravdev@users.noreply.github.com.>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
